apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - pods/logs
      - nodes
    verbs:
      - get
      - list
      - watch
